disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Rian's Website"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Personal website and blog by Rian Finnegan"

[params.author]
  name = "Rian Finnegan"
  email = "rian.finnegan@gmail.com"
  image = "Rian_lookingaway2020.png"
  imageQuality = 96
  headline = "Essays on various topics"
  bio = "Welcome to my personal website where I share thoughts on technology, software development, and various other topics."
  links = [
    { email = "mailto:rian.finnegan@gmail.com" },
    { github = "https://github.com/xtellurian" },
  ]
