name: Build

on:
  push:
    branches:
      - source # default branch
      - main
      - master
      - vnext/dotnet
      - "*"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: edge
        run: dotnet restore
      - name: Build
        working-directory: edge
        run: dotnet build

      - name: Publish
        run: dotnet publish edge -c Release -o public

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/wwwroot
          publish_branch: master # deploying branch
